### ISSUE TITLE
[Feature Request] Increase Cover Art on Now Playing

### ISSUE THREAD

**Issue by chyron8472** [mattttvaughn/chronicle#13]
Please increase the cover art size on the Now Playing screen.

Current view of Now Playing: https://i.imgur.com/RAx3gSi.jpg

Mock-up of proposed view: https://i.imgur.com/9VDFpbg.jpg

**Comment by mattttvaughn** [comment]
Thanks for opening the ticket

Looks like this improvement has already made its way into develop (hasn't been publicized anywhere, not your fault for not knowing. Don't let this stop you from opening similar issues in the future!). Going to close this.

Hmu on discord if this isn't the case and I can reopen it
