### ISSUE TITLE
Rewinding 10 seconds multiple times crashes plex

### ISSUE THREAD

**Issue by pmayeur** [mattttvaughn/chronicle#28]
If I hit rewind 10 seconds like 10 times quickly the plex server crashes and needs to be restarted

**Comment by mattttvaughn** [comment]
1. What version of Plex server are you running?

2. What are the file lengths in your book like? Are you rewinding over multiple tracks or can you reproduce this behavior just rewinding in the same track?

**Comment by pmayeur** [comment]
Plex 1.25.4.5468

Single track. 11 hour book

**Comment by pmayeur** [comment]
I think this might not be chronicle. I am having issues with plex when not using chronicle. I have reported to plex and will debug with them -- https://forums.plex.tv/t/server-crashing-multiple-times-per-day/776658

Will report back here when I know more

**Comment by pmayeur** [comment]
OK not  saying it is caused by Chronicle because I think other stuff can also make it crash, but I can consistent reproduce using "rewind a bunch in chronicle" 

Here are plex logs -- https://we.tl/t-8XbHiIDlI9

**Comment by mattttvaughn** [comment]
I guess obv question is does this repro on normal Plex app or PlexAmp? 

Chronicle is just treating the file as a blob being served by a file server here, not much we could do on the Chronicle end besides growing the back buffer (# seconds of previous playback we keep in memory) AFAIK.

If more people report this issue might be worth looking into but have a feeling it might be an edge case of a file with really big chunk/block/keystone size (don't know the technical term) that Plex is handling poorly
