### ISSUE TITLE
Feature Request: Android Auto support

### ISSUE THREAD

**Issue by Oublic** [mattttvaughn/chronicle#3]
There is no interface for Chronicle appearing on Android Auto. This means I'm unable to use Android Auto to play/pause playback. I can use the phone to control playback and the audio comes through, but that defeats the purpose.

Running Android 12 latest beta on a Pixel 3.
I've gone in to Customize on Android Auto to make sure that the app isn't simply hidden and that's not the case.

**Comment by mattttvaughn** [comment]
Auto support has to be added manually, it doesn't come baked-in with Android's media system, so I've tagged this as an enhancement. Editing the issue title if GitHub lets me to indicate that this ticket includes a feature request for Auto support.

But good news is most of the work is in place for Auto, just hidden behind a flag rn.

To enable Auto support for Chronicle:
* Uncomment the commented-out lines in `app/src/main/AndroidManifest.xml` 
* Turn `FEATURE_FLAG_IS_AUTO_ENABLED` to true in `app/src/main/.../application/Constants.kt`
* [Enable developer mode in Auto](https://support.google.com/androidauto/thread/9008705/psa-how-to-enable-developer-mode-in-the-updated-android-auto-app?hl=en)

Not planning to release until [Android Media Controller](https://github.com/googlesamples/android-media-controller) test suite is passing consistently

**Comment by mrmorganmurphy** [comment]
Was able to clone & build for the first time and enable the Auto changes.
Happy to find Auto support enabled from the login screen. 

One suggestion for the Auto interface is to add a playback-speed option as I change the playback speed when driving.
Something like what Pocket Casts uses that is a tap to cycle through the playback speeds.
![image](https://user-images.githubusercontent.com/22598031/135923119-d4bcd82e-8450-43fa-b0c4-6b55dfe76d93.png)

**Comment by mattttvaughn** [comment]
Really glad to hear the build worked out of the box! Thanks for confirming 

Playback speed action in Auto makes sense to me, can't think of anything better to slot in there. And if pocket casts implements it there's no reason we couldn't also. Could you create an issue for that @mrmorganmurphy?

**Comment by ggrensteiner** [comment]
Just wanted to report this is working in AA (devmode) on Android 12 as well. I also commented out the LeakCanary stuff since it seems like it's keeping itself in line and I just can't be bothered.
