### ISSUE TITLE
Show times while scrubbing

### ISSUE THREAD

**Issue by hskrtich** [mattttvaughn/chronicle#37]
When scrubbing a book the app currently doesn't show the time that you are scrubbing to so its hard to tell where you are scrubbing to.

**Comment by mattttvaughn** [comment]
Yea this could use a revisit.

Want to say I ran into some problems with this in the past (maybe since progress is continuously updated it will jump between playback time and seeking time)

But at the very least we could show a tooltip on seekbar selection with the seeked to time
