### ISSUE TITLE
Feature Request: Android Auto Variable Speed Playback

### ISSUE THREAD

**Issue by mrmorganmurphy** [mattttvaughn/chronicle#4]
Add to the Android Auto interface to include a variable speed playback button like in Pocket Casts.
![135923119-d4bcd82e-8450-43fa-b0c4-6b55dfe76d93](https://user-images.githubusercontent.com/22598031/135932525-09a4da6f-d849-41e4-88b1-5c3fda89a7df.png)

Originally mentioned in [issue #3](https://github.com/mattttvaughn/chronicle/issues/3#issuecomment-933846019)

**Comment by AwsomeFox** [comment]
Created a draft pr with a speed control button added for discussion.

**Comment by mattttvaughn** [comment]
Merged a bit back and is now distributed in the latest GitHub release
