### ISSUE TITLE
Manually mark as "Played/Watched" does nothing

### ISSUE THREAD

**Issue by Neipas09** [mattttvaughn/chronicle#47]
When I open an audiobook that I've already listened to and click on the eye icon at the top right and mark the book as watched/played. The audiobook does not get the blue bar underneath it indicating that it has been listened to.

**Comment by mattttvaughn** [comment]
Yep I can confirm this behavior. The original intention was for completed books to hide the progress bar but for there to be a little "dog ear" triangle indicator in the top corner to indicate played/unplayed. 

Instead we ended up with no progress indicator and no "dog ear" indicator. Either implementation would be fine if anyone's interested in picking up this work
