### ISSUE TITLE
Feature Request: change download location 

### ISSUE THREAD

**Issue by kilmerc** [mattttvaughn/chronicle#49]
Right now when I click download location it just shows me where they are located, but I would like the ability to direct to a different directory. Thanks for all your efforts!

**Comment by mattttvaughn** [comment]
This brings us into the tricky Android issues world. Currently the app doesn't have to wrangle with permissions issues by storing downloaded files in a directory specifically created for it (this works for internal storage, but also weird storage like SD cards).

We'd have to start jumping through hoops of perrmissions, revoked permissions, and Android 10+s whack new file access.

There's also a whole can of worms re: downloaded files being named by internal ID

Tbh I'm probably not planning on adding anything like this anytime soon, just given the low RoI I'd expect from it

**Comment by kilmerc** [comment]
That does sound complex. Thanks for the detailed response!

**Comment by mattttvaughn** [comment]
Closing for now. Open to revisiting this in the future, but RoI pretty low at this point
