### ISSUE TITLE
Cancel notification action is not visible

### ISSUE THREAD

**Issue by lks-nbg** [mattttvaughn/chronicle#56]
With PR #52 I added two more actions to the notification, which now totals to six actions. Since the limit (MAX_MEDIA_BUTTONS) is five the cancel button to manually kill the notification and the service is no longer visible. 

Not sure what the preferred actions are.

**Comment by mattttvaughn** [comment]
A few thoughts....

1. The cancel notification icon is mostly just a band-aid solution to the issue where the notification freezes in "playing" mode (#40), which prevents the notification from being dismissed. If we fix #40 this is no longer an issue

2. Android 11+ doesn't allow for media notifications to be dismissed, so the cancel action is unnecessary for all those devices.

Not sure how much work #40 will be, but maybe we could aim to fix it before shipping 0.52.0

**Comment by mattttvaughn** [comment]
Closing as the cancel notification action is no longer needed due to #40. Removed cancel button in a9a0650d
