### ISSUE TITLE
BT controls changed 0.52.0

### ISSUE THREAD

**Issue by runningslow81** [mattttvaughn/chronicle#69]
I frequently use Bluetooth earbuds, primarily a pair OnePlus Buds.  In previous versions of the app, double tapping the right earbud would skip forward 30 seconds and double tapping the left would skip back 10 seconds. This behavior is similar to other apps I use.

Starting with version 0.52.0, the behavior is now skipping to the end of the chapter or to the previous chapter.  I saw in the changelog that this function was added.

It confused the hell out me when I went for a run last night and I tried skipping back to hear something again.

Could it be possible to specify a preference for which controls react to Bluetooth commands?  The ability to skip forward or back a few seconds makes much more sense for my use case of the app with earbuds. I'm not often listening to a book where I suddenly need to skip chapters at a time.

**Comment by mattttvaughn** [comment]
Thanks, seeing the same change on my BT earbuds. I'd think this behavior should probably stay as it was by default, that tracks with most apps I've used before.

I'm going to undo this change, but I'm open to an exploration of what these various keycodes do and changing them down the line.

Also open to the suggestion of letting users choose to skip chapters or jump x seconds. If that would be preferable for anyone feel free to write up an issue if it is.

cc @lks-nbg holler if you've got opinions on this

Change here: https://github.com/mattttvaughn/chronicle/blob/3031536b36594821eddd29530f4bfe5238f2b2e3/app/src/main/java/io/github/mattpvaughn/chronicle/features/player/AudiobookMediaSessionCallback.kt#L156

**Comment by lks-nbg** [comment]
I think most headphones only support the basic actions KEYCODE_MEDIA_NEXT & KEYCODE_MEDIA_PREVIOUS. For a music player I would say that skipping to the next or previous track is the right choice, but for an audiobook player skipping forwards or backwards is probably the preferred behavior, especially since it has worked that way in the past.

**Comment by mattttvaughn** [comment]
Reverted in 33e0c06f8d1251c14860eb60c0e0d3bd3d1d792a.
