### ISSUE TITLE
[Feature Request] Custom playback speeds

### ISSUE THREAD

**Issue by theswordsmahin** [mattttvaughn/chronicle#7]
It would be great if instead of a hard coded list of playback speeds we had a counter or some other interface for entering in custom playback speeds, ie "1.35"

**Comment by mattttvaughn** [comment]
Definitely doable in a technical sense and a good idea for improvement imo. Would just require a new interface.

If anyone wants to contribute design ideas (rough or polished, anything is useful) feel free to post them in the comments here
