### ISSUE TITLE
Feature request: Percentage/progress

### ISSUE THREAD

**Issue by rollecode** [mattttvaughn/chronicle#71]
Right now it's not clear how much I have listened. It would be great to have percentage of how much is read and a progress bar. Take a look in BookBeat app for example.

**Comment by mattttvaughn** [comment]
What screen are you referring to here? Library/home screen show a little progress bar along the bottom of books, and the book details screen shows the progress in text form (like 12:34:45/23:45:56).

**Comment by rollecode** [comment]
Any screen. I don't see any progress bars (Google Play version). But the most important part is the overall percent which is important, timestamps are no use for updating the Goodreads progress for example. It would be great to see like "45% read".

**Comment by AnDr3w7911** [comment]
I put in a pull request that will display the progress in the format `7:44:39/19:40:57 39%` on the Audiobook details page and the currently playing page

**Comment by tknorris** [comment]
+1 to this. It's important for updating goodreads.com progress

**Comment by rollecode** [comment]
> I put in a pull request that will display the progress in the format `7:44:39/19:40:57 39%` on the Audiobook details page and the currently playing page

This is a good start. Can it be merged and released? @mattttvaughn

**Comment by mattttvaughn** [comment]
> > I put in a pull request that will display the progress in the format `7:44:39/19:40:57 39%` on the Audiobook details page and the currently playing page
> 
> This is a good start. Can it be merged and released? @mattttvaughn 

I'm aware of this PR and meant to get around to it the past weekend, just been a little busy. This weekend for sure 😬

**Comment by rollecode** [comment]
Awesome, thanks in advance! :) No rush.

**Comment by mattttvaughn** [comment]
Closed by #86, thanks to @AnDr3w7911
