### ISSUE TITLE
Request For Finer Speed Controls

### ISSUE THREAD

**Issue by homemadepickles** [mattttvaughn/chronicle#75]
Professional readers make great audiobooks, but often talk too slow. Adding 1.05x and 1.10x speed options would be amazing, as 1.2x is just a little too fast sometimes. 

Other than that, I'm enjoying the app, and it's development. I weep tears of joyous relief I don't have to use the native Plex app anymore.

**Comment by mattttvaughn** [comment]
Great news- a new speed chooser was merged into the app in #66 and will be available in the next release. Specificity of 0.05x, from 0.5x to 3.0x

![Screenshot_20220416-100027.jpg](https://user-images.githubusercontent.com/58408581/163677823-47bb7e0c-544f-404c-9ac8-af37ba7f9b57.jpg)

**Comment by mattttvaughn** [comment]
And thanks for posting the issue regardless!

I don't expect people to poke through PRs before posting issues

**Comment by homemadepickles** [comment]
I'm excited! Thanks!
