### ISSUE TITLE
Usability: Sleep timer

### ISSUE THREAD

**Issue by SamPlusPlus** [mattttvaughn/chronicle#94]
I use the chronicle audiobook app for the first time and ran into a usability issue. My phone was randomly beeping in my pocket and it took me a long time to figure out why. It turns out I had listened to an audiobook on The chronicle app earlier in the day in the app was still running in the background. Presumably the sleep timer still works in the background thread and when the phone was in my pocket and I was walking it was enough to trigger the shake and beep. The problem is by the time I pulled my phone out of my pocket I often did not see the sleep timer extended message.  One tiny possible suggestion would be to prefix the sleep timer extended message with the word chronicle: as to leave the user a breadcrumb as to what app is beeping in the background. I don't know if there's a better solution in terms of not allowing shake to extend timer when the app is not running in the foreground and if there's a reason for that.

Either way not 100% sure what is the best solution just sharing an experience and if there is any way to make it more clear.

**Comment by mattttvaughn** [comment]
Closed by #95, thanks!
